base_url = "https://archive.open-run.org"
title = "Reddit Archive"
default_language = "en"
build_search_index = false
generate_sitemap = true
compile_sass = false
minify_html = true
generate_feeds = true
feed_limit = 64

[link_checker]
internal_level = "warn"
external_level = "warn"

[markdown]
render_emoji = true
external_links_target_blank = true
